#!/usr/bin/env bash
set -ex
IFS='_' read -r -a array <<< $1
#REFERENCE=${array[0]}
REFERENCE=GDSC1
TRANSFER=PDTX
#TRANSFER=${array[1]}
echo "TCRP prediction is being performed on ${TRANSFER}, trained on ${REFERENCE}"
bash tcrp_model/created_models/created_models_${REFERENCE}_${TRANSFER}/run_baselines.sh
bash tcrp_model/${REFERENCE}_${TRANSFER}_commands.sh
python3 tcrp_model/model_comparisons/plot_results.py --reference ${REFERENCE} --tissue ${TRANSFER}
